### PR TITLE
Fail sauce

### PR DESCRIPTION
**Pull request by Sqeaky**
I did a ton work, and this led to the first Jagati that significantly reduced the CMake workload in each package. This should eliminate the need to list details of each package beyond needing a to call IncludeJagatiPackage.

### CODE REVIEW

**Comment by MakoEnergy** [comment]
1) You appear to have some repeat code at lines 485 and 528.
2) On line 595 you list "-pedantic" as a compiler option, but unlike all the other options listed it doesn't have any accompanying documentation.
3) Around line 636 where non-nix compiler options are being set the documentation should probably be above the where the flags are set, for consistency.  Additionally all the options set on the second line are without documentation.  Lastly, if these are meant to be for MSVC then I feel an explicit check for MSVC should be used instead of assumed when non-nix.  It'll probably be a non-issue regardless but it feels more clear with intent as well as future proofing should another platform come along.
4) On line 828 you appear to split a file name and extension, but then don't use the variables beyond putting them back together right after.

**Comment by Sqeaky** [comment]
And this is after like 3 full passes through the file for cleanup, imagine how bad it was before!

**Comment by Sqeaky** [comment]
1. Wow, that was old, removed.
2. -pendantic removed, is entirely replaced by -pedantic-errors.
3. Dox moved and check and semi-sarcastic message added.
4. Removed

In the future could we use macro names instead of, or in addition to, line numbers?

I also added some other changes I was working on.

**Comment by MakoEnergy** [comment]
In the CreateCoverageTarget macro at around line 825 you removed one line that splits the filename, but still use the file extension variable(which is unset as is, I believe).  Rest looks good.

**Comment by Sqeaky** [comment]
Oh I must be tired again....

It belongs in there, the whole extension concatenation noise, was originally correct. It makes the difference between finding the gcno (the coverage data) files and not finding them.

I tested with:  rm CMakeCache.txt && cmake ../Mezz_Foundation -GNinja -DMEZZ_PackageDirectory=/home/sqeaky/Code -DMEZZ_CodeCoverage=true && ninja && ./Foundation_Tester && ./Foundation_Tester && ninja FoundationCoverage

and pushed changes.

**Comment by MakoEnergy** [comment]
Weird, but alright.  Everything else looks good.

**Comment by Sqeaky** [comment]
This closes #8 .

**Pull request merged**
