### PR TITLE
Initial commit of Index file and associated tools.

### PR DESCRIPTION
**Pull request by Sqeaky**

### CODE REVIEW

**Comment by Sqeaky** [comment]
I am curious about you opinion on the format of the file?

**Comment by MakoEnergy** [comment]
Format looks good.  Took me a moment to parse.  I also had to do a double take on the function name because I thought it might clash with the other macro in the main Jagati file.  "AddJagatiPackage" vs "AddJagatiLibrary".  I'd consider renaming it slightly so they aren't so close, but not a big issue either way.

**Comment by Sqeaky** [comment]
Should we Drop the "Add"?

**Comment by MakoEnergy** [comment]
"SetPackageURL" was my first thought.

**Comment by Sqeaky** [comment]
We might overload this with other behavior later, so I didn't want to restrict this to URLs.

**Comment by Sqeaky** [comment]
I was going to re-submit with "JagatiPackage"

**Comment by MakoEnergy** [comment]
"SetPackageMetadata"?  I'm out of suggestions after that.

**Comment by Sqeaky** [comment]
I was thinking of having this function be a noun to make this file look as declarative as possible. We could go with "PackageMetadata".

**Pull request merged**
