### PR TITLE
Proposed bigleap

### PR DESCRIPTION
**Pull request by Sqeaky**
This is a pretty big deal, we need to be sure that this passes in CI and that we minimize types and issues because this will be the last major change before the Jagati Refactor.

### CODE REVIEW

**Comment by Sqeaky** [comment]
This will eventually be Jagati 0.20.0 and will require updates in Mezz_StaticFoundation and Mezz_Test.

**Comment by MakoEnergy** [comment]
In the Macro "CreateLocations" what is the purpose/use case of creating the normal folders expected in a Jagati package?  The generated source/headers make sense, as they are generated.  But presumably those folders will already exist by the time the Jagati is run, right?

**Comment by Sqeaky** [comment]
I first made CreateLocations because I was unsure about the spelling of the folders for a brief moment (casing) and it occurred to me that new users could be even more befuddled. So I had it make the folders so it couldn't be spelled/cased it wrong.

I realize this breaks the no writing to the source dir rule the Jagati other has, but if the folders exist then it changes nothing.

I figured we could write a tutorial that has people start with nothing but cmake and a text editor and winding up with a working directory of code. I hadn't written that yet because I considered it out of scope.

**Comment by Sqeaky** [comment]
Any change to the Jagati will change the SHA and we will need to change the SHAs in the Mezz_Test and Mezz_StaticFoundation Repos, because they point at this PR instead of a version tag. I can handle doing this, but I thought you should know why the CI tests will fail.

**Comment by MakoEnergy** [comment]
Good to know!  I was nearly about to panic at the thought that changes to docs would fail.

**Comment by Sqeaky** [comment]
We need Unit Tests for my grammar and spelling.

**Comment by MakoEnergy** [comment]
Then I'd be obsolete!

**Comment by Sqeaky** [comment]
I am updating the StaticFoundation SHA: https://github.com/BlackToppStudios/Mezz_StaticFoundation/pull/29

**Comment by Sqeaky** [comment]
Now doing the Mezz_Test SHAs: https://github.com/BlackToppStudios/Mezz_Test/pull/25

**Comment by Sqeaky** [comment]
SHAs passed and Merged, restarting these tests.

**Pull request merged**
